# Generated by Django 5.2.7 on 2025-11-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='List created on 2025-11-07', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('other', 'Other')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_by', to=settings.AUTH_USER_MODEL)),
                ('brought_to', models.ManyToManyField(related_name='brought_to', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='routine_app.list')),
            ],
        ),
    ]
