# Generated by Django 5.1.3 on 2025-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('recurring', 'Recurring'), ('non-recurring', 'Non-Recurring')], default='recurring', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recurrence_interval', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default=False, max_length=10, null=True)),
            ],
        ),
    ]
