# Generated by Django 5.2.5 on 2025-09-10 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('other', 'Other')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_by', to=settings.AUTH_USER_MODEL)),
                ('brought_to', models.ManyToManyField(related_name='brought_to_you', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
